### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yzpopulation** [blqw/blqw.HttpRequest#2]
你给的demo中
  var www = new Httpdoer("www.baidu.com");
            www.Body.ContentType = HttpContentType.Json;
            www.Method = HttpRequestMethod.Post;
            www.Body.Wirte(Encoding.UTF8.GetBytes("{'a':1}"));
            //           www.Body.AddModel(new { a = 1, b = "fdsfdas", c = new { d = true, e = DateTime.Now, f = new[] { 1, 2, 3, 4, 5 } } });
            var str = www.GetString();
            Console.WriteLine(str);
执行 str为空！

**Comment by yzpopulation** [comment]
![](http://i.imgur.com/4SXmglP.png)

**Comment by blqw** [comment]
最新的版本测试没有这个问题, 请尝试下
